# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fly_match.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1924, 868)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_viewer = ModelViewer(self.centralwidget)
        self.frame_viewer.setMinimumSize(QtCore.QSize(1341, 611))
        self.frame_viewer.setObjectName("frame_viewer")
        self.verticalLayout_2.addWidget(self.frame_viewer)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(241, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.seq_select_btn = QtWidgets.QPushButton(self.frame_2)
        self.seq_select_btn.setObjectName("seq_select_btn")
        self.verticalLayout.addWidget(self.seq_select_btn)
        self.seq_disp = QtWidgets.QLineEdit(self.frame_2)
        self.seq_disp.setObjectName("seq_disp")
        self.verticalLayout.addWidget(self.seq_disp)
        self.mov_select_btn = QtWidgets.QPushButton(self.frame_2)
        self.mov_select_btn.setObjectName("mov_select_btn")
        self.verticalLayout.addWidget(self.mov_select_btn)
        self.mov_disp = QtWidgets.QLineEdit(self.frame_2)
        self.mov_disp.setObjectName("mov_disp")
        self.verticalLayout.addWidget(self.mov_disp)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_spin = QtWidgets.QSpinBox(self.frame_3)
        self.frame_spin.setObjectName("frame_spin")
        self.gridLayout.addWidget(self.frame_spin, 2, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.load_frames_btn = QtWidgets.QPushButton(self.frame_3)
        self.load_frames_btn.setObjectName("load_frames_btn")
        self.gridLayout.addWidget(self.load_frames_btn, 0, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setMaximumSize(QtCore.QSize(171, 191))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_27 = QtWidgets.QLabel(self.frame_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.frame_7)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 1, 0, 1, 3)
        self.label_29 = QtWidgets.QLabel(self.frame_7)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 2, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 0, 1, 1)
        self.u_cam1_spin = QtWidgets.QSpinBox(self.frame_7)
        self.u_cam1_spin.setObjectName("u_cam1_spin")
        self.gridLayout_4.addWidget(self.u_cam1_spin, 3, 1, 1, 1)
        self.v_cam1_spin = QtWidgets.QSpinBox(self.frame_7)
        self.v_cam1_spin.setObjectName("v_cam1_spin")
        self.gridLayout_4.addWidget(self.v_cam1_spin, 3, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_7)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 4, 0, 1, 1)
        self.u_cam2_spin = QtWidgets.QSpinBox(self.frame_7)
        self.u_cam2_spin.setObjectName("u_cam2_spin")
        self.gridLayout_4.addWidget(self.u_cam2_spin, 4, 1, 1, 1)
        self.v_cam2_spin = QtWidgets.QSpinBox(self.frame_7)
        self.v_cam2_spin.setObjectName("v_cam2_spin")
        self.gridLayout_4.addWidget(self.v_cam2_spin, 4, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.frame_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 5, 0, 1, 1)
        self.u_cam3_spin = QtWidgets.QSpinBox(self.frame_7)
        self.u_cam3_spin.setObjectName("u_cam3_spin")
        self.gridLayout_4.addWidget(self.u_cam3_spin, 5, 1, 1, 1)
        self.v_cam3_spin = QtWidgets.QSpinBox(self.frame_7)
        self.v_cam3_spin.setObjectName("v_cam3_spin")
        self.gridLayout_4.addWidget(self.v_cam3_spin, 5, 2, 1, 1)
        self.save_uv_shift_btn = QtWidgets.QPushButton(self.frame_7)
        self.save_uv_shift_btn.setObjectName("save_uv_shift_btn")
        self.gridLayout_4.addWidget(self.save_uv_shift_btn, 6, 0, 1, 3)
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(301, 191))
        self.frame_4.setMaximumSize(QtCore.QSize(301, 191))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(49, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 4, 1, 1)
        self.L_scale_spin = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.L_scale_spin.setObjectName("L_scale_spin")
        self.gridLayout_5.addWidget(self.L_scale_spin, 0, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 2, 6)
        self.ry_L_spin = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.ry_L_spin.setObjectName("ry_L_spin")
        self.gridLayout_5.addWidget(self.ry_L_spin, 2, 1, 3, 2)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 2, 1)
        self.state_L_table = QtWidgets.QTableWidget(self.frame_4)
        self.state_L_table.setMinimumSize(QtCore.QSize(141, 121))
        self.state_L_table.setObjectName("state_L_table")
        self.state_L_table.setColumnCount(0)
        self.state_L_table.setRowCount(0)
        self.gridLayout_5.addWidget(self.state_L_table, 4, 3, 4, 3)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 5, 0, 1, 1)
        self.b1_L_spin = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.b1_L_spin.setObjectName("b1_L_spin")
        self.gridLayout_5.addWidget(self.b1_L_spin, 5, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(128, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 6, 0, 1, 3)
        self.reset_L_btn = QtWidgets.QPushButton(self.frame_4)
        self.reset_L_btn.setObjectName("reset_L_btn")
        self.gridLayout_5.addWidget(self.reset_L_btn, 7, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(301, 191))
        self.frame_5.setMaximumSize(QtCore.QSize(301, 191))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(49, 23, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.R_scale_spin = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.R_scale_spin.setObjectName("R_scale_spin")
        self.gridLayout_2.addWidget(self.R_scale_spin, 0, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 2, 5)
        self.ry_R_spin = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.ry_R_spin.setObjectName("ry_R_spin")
        self.gridLayout_2.addWidget(self.ry_R_spin, 2, 1, 3, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 2, 1)
        self.state_R_table = QtWidgets.QTableWidget(self.frame_5)
        self.state_R_table.setMinimumSize(QtCore.QSize(141, 121))
        self.state_R_table.setObjectName("state_R_table")
        self.state_R_table.setColumnCount(0)
        self.state_R_table.setRowCount(0)
        self.gridLayout_2.addWidget(self.state_R_table, 4, 2, 4, 3)
        self.label_11 = QtWidgets.QLabel(self.frame_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.b1_R_spin = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.b1_R_spin.setObjectName("b1_R_spin")
        self.gridLayout_2.addWidget(self.b1_R_spin, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(128, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 6, 0, 1, 2)
        self.reset_R_btn = QtWidgets.QPushButton(self.frame_5)
        self.reset_R_btn.setObjectName("reset_R_btn")
        self.gridLayout_2.addWidget(self.reset_R_btn, 7, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_5)
        spacerItem4 = QtWidgets.QSpacerItem(1459, 188, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.save_lbl_btn = QtWidgets.QPushButton(self.frame_6)
        self.save_lbl_btn.setObjectName("save_lbl_btn")
        self.gridLayout_3.addWidget(self.save_lbl_btn, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(108, 137, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlyMatch"))
        self.seq_select_btn.setText(_translate("MainWindow", "Select sequence"))
        self.mov_select_btn.setText(_translate("MainWindow", "Select movie folder"))
        self.label.setText(_translate("MainWindow", "Frame nr:"))
        self.load_frames_btn.setText(_translate("MainWindow", "load frames"))
        self.label_27.setText(_translate("MainWindow", "uv-shift:"))
        self.label_29.setText(_translate("MainWindow", "u:"))
        self.label_32.setText(_translate("MainWindow", "v:"))
        self.label_28.setText(_translate("MainWindow", "cam 1:"))
        self.label_30.setText(_translate("MainWindow", "cam 2:"))
        self.label_31.setText(_translate("MainWindow", "cam 3:"))
        self.save_uv_shift_btn.setText(_translate("MainWindow", "save uv-shift"))
        self.label_2.setText(_translate("MainWindow", "Left wing state:"))
        self.label_3.setText(_translate("MainWindow", "scale:"))
        self.label_5.setText(_translate("MainWindow", "pitch:"))
        self.label_14.setText(_translate("MainWindow", "bending:"))
        self.reset_L_btn.setText(_translate("MainWindow", "reset state"))
        self.label_23.setText(_translate("MainWindow", "Right wing state:"))
        self.label_7.setText(_translate("MainWindow", "scale:"))
        self.label_9.setText(_translate("MainWindow", "pitch:"))
        self.label_11.setText(_translate("MainWindow", "bending:"))
        self.reset_R_btn.setText(_translate("MainWindow", "reset state"))
        self.save_lbl_btn.setText(_translate("MainWindow", "save label"))


from ModelViewer import ModelViewer
